version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: steam_db
    environment:
      POSTGRES_USER: steam_user
      POSTGRES_PASSWORD: steam_pass
      POSTGRES_DB: steam_prices
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: steam_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
